# Change these first
owner: jeffery-mclaughlin # Your GitHub organization or username, where this repository lives
repo: quianna.co # The name of this repository 

sites:
  - name: quianna.co
    url: https://quianna.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: quianna.co
  baseUrl: /quianna.co
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: QuiannaCo
  introTitle: "**Upptime** dashboard for quianna.co"
  introMessage: Current status is...
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/jeffery-mclaughlin/quianna.co

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
